# -*- coding: utf-8 -*-
"""CV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152T3BFX1HG12aR7gX9xUtyH1K0fCuO4q
"""

import streamlit as st
def main():
    st.set_page_config(page_title="Passant El-Tonsy - CV", page_icon=":briefcase:", layout="centered")
    image_path = "photo_2025-01-03_12-05-21.jpg"
    print(image_path)
    st.markdown(
        """
        <style>
            .circular-image {{
                border-radius: 50%;
                overflow: hidden;
                width: 200px;
                height: 200px;
                object-fit: cover;
            }}
        </style>
        """,
        unsafe_allow_html=True,
    )
    st.markdown(f'<img src="{image_path}" class="circular-image">', unsafe_allow_html=True)

    
    # Header Section
    st.title("Passant El-Tonsy")
    st.markdown("**Aspiring Computer Engineer | Passionate about Machine Learning & Computer Vision**")
    st.write("Cairo, Egypt | +20 1158947220 ")
    st.write("[passanteltonsy@gmail.com](mailto:passanteltonsy@gmail.com)")
    st.write("[GitHub](https://github.com/PassantELTonsy) | [LinkedIn](https://www.linkedin.com/in/passant-el-tonsy-a52b42230) | [Kaggle](https://www.kaggle.com/passanteltonsy)")

    # Skills Section
    st.header("Skills")
    skills = [
        "Programming: C++, Java, Python, MATLAB",
        "Machine Learning: Pytorch, Deep Learning, NLP",
        "Data Analysis: Exploratory Data Analysis, Data Cleaning, Data Mining",
        "Software & Systems: Operating Systems, Computer Organization, Network Fundamentals",
        "Other: Technical Report Writing, Time Management, Multitasking"
    ]
    for skill in skills:
     st.markdown(f"- {skill}")
    
    # Education Section
    st.header("Education")
    st.write("**Faculty of Engineering at Shoubra - Benha University**")
    st.write("B.Sc. in Computer Engineering 2020-2025")
    st.write("Current GPA: 2.83")

    # Experience Section
    st.header("Experience")
    st.write("**Team Leader (2024-2025)**")
    st.markdown("- Developed a project timeline and milestones for ML-based projects.")
    st.markdown("- Proposed solutions in Speech Recognition, NLP, and Rendering Avatars.")

    st.write("**Search Quality Rater at RWSGroup (2024)**")
    st.markdown("- Evaluated search results and annotated data.")

    st.write("**Lead Swimming Coach at Go Swimming Academy (2018-present)**")
    st.markdown("- Provided technical instruction and team management.")

    # Projects Section
    st.header("Projects")
    projects = {
        "TALKIN’ HANDS": {
            "description": "Converts spoken Arabic into sign language glosses rendered through a 3D avatar.",
            "image":None,
            "video":None
        },
        "Optimized Flight Trip": {
            "description": "Applied AI algorithms to optimize flight itineraries, deployed via Streamlit.",
            "image":"Optimized flight Trip Poster.png",
            "video": "DEMO.mp4" ,  
           
        },
        "Customer Service Expert System": {
            "description": "Replied to FAQs using Prolog.",
            "image":None,
            "video":"Customer Service Support Demo.mp4"
            
        },
        "Shutter Bug Game": {
            "description": "Developed an interactive 2D game in Processing.",  
            "video": "ShutterBugDemo.mp4" ,
            "image":None

        }
    }

    selected_project = st.selectbox("Select a project", list(projects.keys()))
    
    # Display the description and content (image/video) of the selected project
    if selected_project:
        st.write(f"**{selected_project}:** {projects[selected_project]['description']}")
        # Show the image if available
        if projects[selected_project]["image"]:
            st.image(projects[selected_project]["image"], width=400)  

        # Show the video if available
        if projects[selected_project]["video"]:
            st.video(projects[selected_project]["video"], format="video/mp4")







    
    
    # Courses Section
    st.header("Courses")
    courses = [
        "Data Analysis Challenger Track (Udacity)",
        "Machine Learning Specialization (Andrew Ng)",
        "HCIA Cloud Computing V5.0 (Huawei ICT)",
        "Network Fundamentals (CompTIA Course, Maspero)",
        "NLP Workshop (People of Data)"
    ]
    for course in courses:
        st.markdown(f"- {course}")

    # Languages & Extracurricular Activities
    st.header("Languages")
    st.markdown("- English, German, French")

    st.header("Extracurricular Activities")
    st.write("**Vice President at East Nasr-City Student Union (2015-2018)**")
    st.markdown("- Managed website design, content, and SEO.")
    st.markdown("- Worked on marketing, branding, and logo design.")


if __name__ == "__main__":
    main()

