# -*- coding: utf-8 -*-
"""CV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152T3BFX1HG12aR7gX9xUtyH1K0fCuO4q
"""

import streamlit as st
def main():
    st.set_page_config(page_title="Passant El-Tonsy - CV", page_icon=":briefcase:", layout="centered")
    image_path = "cropped_image.png"
    st.image(image_path, width=200)
    
    # Header Section
    st.title("Passant El-Tonsy")
    st.markdown("**Aspiring Computer Engineer | Passionate about Machine Learning & Computer Vision| Data Annotation Specialist | Former EOI'2018**")
    st.write("Cairo, Egypt | +20 1158947220 ")
    st.write("[passanteltonsy@gmail.com](mailto:passanteltonsy@gmail.com)")
    st.write("[GitHub](https://github.com/PassantELTonsy) | [LinkedIn](https://www.linkedin.com/in/passant-el-tonsy-a52b42230) | [Kaggle](https://www.kaggle.com/passanteltonsy)")

    # Achievements Section
    st.header("Achievements")
    st.markdown("- **Top 20 Finalist** in Dell Technologies *Envision the Future* Competition")
    st.markdown("- **2nd Place Winner** at Benha University's 4th Annual Conference on Applied Science for Graduation Project")
    st.image("photo_2025-05-11_13-40-19.jpg", width=400)

    # Skills Section
    st.header("Skills")
    skills = [
        "**Programming**: C++, Java, Python, MATLAB, OOP, Data Structure",
        "**Machine Learning**: Neural Network, Pytorch, Deep Learning, NLP,Probability & Statistics , Discrete Mathematics",
        "**Data Analysis**: Exploratory Data Analysis, Data Cleaning, Data Mining, Text Preprocessing ",
        "**Software & Systems**: Software Engineering, Operating Systems, Computer Organization, Network Fundamentals",
        "**Soft Skills**: Self Learning, Technical Report Writing, Time Management, Multitasking"
    ]
    for skill in skills:
     st.markdown(f"- {skill}")
    
    # Education Section
    st.header("Education")
    st.write("**Faculty of Engineering at Shoubra - Benha University**")
    st.write("B.Sc. in Computer Engineering 2020-2025")
    st.write("Current GPA: 3.00")

    # Experience Section
    st.header("Experience")
    st.markdown(""" 
    **FO Engineer, Huawei**
    - Monitoring IT infrastructure using Huawei systems to ensure high service availability, fault
      detection, troubleshooting and escalation.
      """)
    st.markdown("""
    **Coding Instructor – DEMI Summer Project 2025, iSchool**  
    - Delivered engaging lessons in programming fundamentals to 4th-grade students using a project-based learning approach achieving over 90% in quality review as one of the best tutors.  
    - Helped foster a love for technology and problem-solving among ~30,000 students in early stages.
    """)
    
    st.markdown("""
    **Testing and Automation Trainee – 2025, Algoriza**  
    - Trained on Software Testing Life Cycle (STLC), bug reporting, test case design using ISTQB standards v4.0 and API Testing using Postman.  
    """)

    st.write("**Team Leader (2024-2025)**")
    st.markdown("- Developed a project timeline and milestones for ML-based projects.")
    st.markdown("- Proposed solutions in Speech Recognition, NLP, and Rendering Avatars.")

    st.write("**Search Quality Rater at RWSGroup (2024)**")
    st.markdown("- Evaluated search results and annotated data.")

    st.write("**Head Swimming Coach at Go Swimming Academy (2018-present)**")
    st.markdown("- Provided technical instruction and team management.")
    st.image("photo_2025-01-05_16-35-36.jpg", width=400)

    # Projects Section
    st.header("Projects")
    projects = {
        
        "Optimized Flight Trip": {
            "description": "This Project explores the application of searching algorithms e.g. BFS-DFS-A*-Greedy-UCS-IDS-DLS in optimizing flight trip planning. By harnessing the power of AI, we aim to develop a system capable of efficiently navigating complex flight networks to identify the most cost-effective and time-efficient routes. This project not only delves into the technical aspects of AI algorithms but also examines their real-world implications for travellers, airlines, and the broader travel industry.",
            "image":"Optimized flight Trip Poster.png",
            "video": "DEMO.mp4" ,  
           
        },
        "Event Registration System": {
            "description": "The Event Registration System is designed to provide a comprehensive platform for managing events. Check Documentation HERE:https://drive.google.com/file/d/1pI7TWLScOuNfzwQFEXDGSs60WIyoQGSi/view?usp=drive_link",
            "image":"photo_2025-01-05_14-49-08.jpg",
            "video": None ,  
           
        },
        
         
        
        "TALKIN’ HANDS": {
            "description": "Converts spoken Arabic into sign language glosses rendered through a 3D avatar.",
            "image":None,
            "video":"DEMO Talkin Hands.mp4"
            },
       
        "Customer Service Expert System": {
            "description": "Replied to FAQs using Prolog.",
            "image":None,
            "video":"Customer Service Support Demo.mp4"
            
        },
        "Shutter Bug Game": {
            "description": "Developed an interactive 2D game in Processing.",  
            "video": "ShutterBugDemo.mp4" ,
            "image":None

        }
    }

    selected_project = st.selectbox("Select a project", list(projects.keys()))
    
    # Display the description and content (image/video) of the selected project
    if selected_project:
        st.write(f"**{selected_project}:** {projects[selected_project]['description']}")
        # Show the image if available
        if projects[selected_project]["image"]:
            st.image(projects[selected_project]["image"], width=400)  

        # Show the video if available
        if projects[selected_project]["video"]:
            st.video(projects[selected_project]["video"], format="video/mp4")







    
    
    # Courses Section
    st.header("Courses&Certificates")
    courses = [
    "**Data Analysis Challenger Track (Udacity)**\nwww.udacity.com/certificate/e/b3581198-03a3-11ed-95eb-c3542bb3a956",
    "**Machine Learning Specialization (Andrew Ng)**\nhttps://coursera.org/share/a97b04775f9d1d501fee1292f38ab285",
    "**Advanced Learning Algorithms**\nhttps://coursera.org/share/3090067024e664421f7daf295017f556",
    "**HCIA Cloud Computing V5.0 (Huawei ICT)**\nhttps://drive.google.com/file/d/10xjtHSDiFPDHQVtj2-UJa8yhc7pBnG5N/view?usp=sharing",
    "**Network Fundamentals (CompTIA Course, Maspero)**\nhttps://drive.google.com/file/d/1SQgRn047nTbwnAI3Md3XvWa1WoPQRK_T/view?usp=sharing",
    "**AI-Finance Hackathon**\nhttps://drive.google.com/file/d/1JMcD3_8HQM5wU3LDbYztdE2YNSKqqwQw/view?usp=sharing",
    "**NLP Workshop (People of Data)**"
]

    for course in courses:
        parts = course.split('\n') 
        if len(parts) == 2:
                st.markdown(f"- {parts[0]}\n  [{parts[1]}]({parts[1]})")
        else:
                st.markdown(f"- {parts[0]}")

    # Languages & Extracurricular Activities
    st.header("Languages")
    st.markdown("- English, German, French")

    st.header("Extracurricular Activities")
    st.write("**AI Presenter, Google Gemini Academy Event 2025**")
    st.markdown("- Delivered a technical presentation on Google Gemini’s multimodal AI features, deep research mode and educational applications also simplified advanced AI concepts for an audience from multiple
    engineering departments.")
    st.write("**Vice President at East Nasr-City Student Union (2015-2018)**")


if __name__ == "__main__":
    main()

